/**
 * Differential test for the valuation mirror.
 *
 * `_positionValue` and `_morphoSurplusAndShortfall` are internal, so the off-chain side has
 * to reconstruct them from raw Morpho state. The vectors here carry only the raw inputs
 * (collateral, borrowShares, market totals, oracle price) plus the numbers the vault itself
 * reported. The mirror gets the inputs and must land on the same totals.
 *
 * Generated by test/vectors/ValuationVectors.t.sol against real Arbitrum state.
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import {
  dropToleranceFloor,
  healthFactor,
  positionValue,
  totalAssets,
  totalMorphoAssets,
  type PositionInputs,
} from "../src/valuation.js";

const here = dirname(fileURLToPath(import.meta.url));
const raw = JSON.parse(readFileSync(join(here, "vectors/valuation.json"), "utf8")) as { cases: string[] };

interface Scenario {
  positions: PositionInputs[];
  idle: bigint;
  expectedTotalMorphoAssets: bigint;
  expectedTotalAssets: bigint;
}

function marketOf(totalBorrowAssets: bigint, totalBorrowShares: bigint) {
  // Only the borrow side is used by valuation; supply totals, lastUpdate and fee are not.
  return { totalSupplyAssets: 0n, totalSupplyShares: 0n, totalBorrowAssets, totalBorrowShares, lastUpdate: 0n, fee: 0n };
}

function parse(): Scenario[] {
  const byIndex = new Map<number, Scenario>();
  const get = (i: number): Scenario => {
    let s = byIndex.get(i);
    if (!s) {
      s = { positions: [], idle: 0n, expectedTotalMorphoAssets: 0n, expectedTotalAssets: 0n };
      byIndex.set(i, s);
    }
    return s;
  };

  for (const line of raw.cases) {
    const f = line.split(",");
    const kind = f[0];
    const index = Number(f[1]);
    if (kind === "pos") {
      get(index).positions.push({
        position: { supplyShares: 0n, borrowShares: BigInt(f[3]!), collateral: BigInt(f[2]!) },
        market: marketOf(BigInt(f[4]!), BigInt(f[5]!)),
        price: BigInt(f[6]!),
      });
    } else if (kind === "tot") {
      const s = get(index);
      s.idle = BigInt(f[2]!);
      s.expectedTotalMorphoAssets = BigInt(f[3]!);
      s.expectedTotalAssets = BigInt(f[4]!);
    } else {
      throw new Error(`unknown vector kind "${kind}"`);
    }
  }
  return [...byIndex.entries()].sort((a, b) => a[0] - b[0]).map(([, s]) => s);
}

const scenarios = parse();

describe("valuation matches the vault's own reported totals", () => {
  it("parsed every scenario", () => {
    expect(scenarios.length).toBeGreaterThanOrEqual(4);
  });

  scenarios.forEach((s, i) => {
    it(`scenario ${i}: ${s.positions.length} position(s) -> totalMorphoAssets`, () => {
      expect(totalMorphoAssets(s.positions)).toBe(s.expectedTotalMorphoAssets);
    });

    it(`scenario ${i}: ${s.positions.length} position(s) -> totalAssets`, () => {
      expect(totalAssets(s.idle, s.positions)).toBe(s.expectedTotalAssets);
    });
  });
});

describe("oracle failure degrades conservatively", () => {
  /**
   * The contract's try/catch values collateral at zero while still counting the debt.
   * Skipping the position instead would drop the debt too and inflate the total exactly when
   * the vault can least justify it, so a null price must only ever reduce the reported value.
   */
  it("a null price can only lower the total, never raise it", () => {
    const withPrice = scenarios.find((s) => s.positions.length > 0);
    expect(withPrice).toBeDefined();

    const blinded = withPrice!.positions.map((p) => ({ ...p, price: null }));
    expect(totalAssets(withPrice!.idle, blinded)).toBeLessThanOrEqual(
      totalAssets(withPrice!.idle, withPrice!.positions),
    );
  });

  it("a position with debt and a dead oracle becomes pure shortfall", () => {
    const p = scenarios.flatMap((s) => s.positions).find((x) => x.position.borrowShares > 0n);
    expect(p).toBeDefined();

    const v = positionValue({ ...p!, price: null });
    expect(v.surplus).toBe(0n);
    expect(v.shortfall).toBeGreaterThan(0n);
  });
});

describe("drop tolerance floor", () => {
  it("matches the contract's integer arithmetic", () => {
    // assetsBefore * (10_000 - bps) / 10_000, rounding down.
    expect(dropToleranceFloor(1_000_000_000000n, 100n)).toBe(990_000_000000n);
    expect(dropToleranceFloor(999_999n, 100n)).toBe(989_999n); // 989999.01 floors to 989999
    expect(dropToleranceFloor(0n, 100n)).toBe(0n);
    expect(dropToleranceFloor(12345n, 0n)).toBe(12345n);
  });
});

describe("health factor", () => {
  it("is null with no debt, matching the contract's uint max", () => {
    expect(healthFactor({ supplyShares: 0n, borrowShares: 0n, collateral: 1n }, marketOf(0n, 0n), 1n, 1n)).toBeNull();
  });

  it("is WAD-scaled, so 1e18 is the liquidation boundary", () => {
    const p = scenarios.flatMap((s) => s.positions).find((x) => x.position.borrowShares > 0n)!;
    const hf = healthFactor(p.position, p.market, p.price!, 860000000000000000n);
    expect(hf).not.toBeNull();
    // A 2x position at 86% LLTV sits comfortably above 1e18 but well under 2e18.
    expect(hf!).toBeGreaterThan(10n ** 18n);
    expect(hf!).toBeLessThan(2n * 10n ** 18n);
  });
});
