/**
 * Generates typed ABIs from this repo's own `forge build` artifacts.
 *
 * Hand-rolled rather than wagmi-cli for two reasons. It lets us whitelist exactly the
 * contracts the allocator talks to instead of emitting the whole tree, and it runs
 * `forge build` itself, so it is structurally incapable of emitting a stale ABI.
 *
 * This is the main defence against contract/off-chain version skew: the ABIs are generated
 * from the same working tree as the Solidity, on every build, and the output is gitignored
 * so a checked-in copy can never drift from what is actually deployed.
 *
 *   pnpm --filter @morphoagg/core gen
 */

import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../../../..");
const outDir = join(repoRoot, "out");
const generatedDir = join(here, "../src/abi/generated");

/** Artifact name -> exported const name. */
const CONTRACTS: Record<string, string> = {
  MorphoLeverageVault: "vaultAbi",
  RiskLimits: "riskLimitsAbi",
  MorphoSwapExecutor: "swapExecutorAbi",
  IMorpho: "morphoAbi",
  IOracle: "oracleAbi",
};

function readAbi(contract: string): unknown[] {
  // Foundry lays artifacts out as out/<Source>.sol/<Contract>.json. Source file and contract
  // share a name for every contract here, which the check below enforces rather than assumes.
  const path = join(outDir, `${contract}.sol`, `${contract}.json`);
  let raw: string;
  try {
    raw = readFileSync(path, "utf8");
  } catch {
    throw new Error(
      `missing artifact for ${contract} at ${path}\n` +
        `If the contract was renamed, update CONTRACTS in this script.`,
    );
  }
  const parsed = JSON.parse(raw) as { abi?: unknown[] };
  if (!Array.isArray(parsed.abi)) {
    throw new Error(`artifact for ${contract} has no abi array`);
  }
  return parsed.abi;
}

function main(): void {
  console.log("forge build...");
  execFileSync("forge", ["build"], { cwd: repoRoot, stdio: "inherit" });

  mkdirSync(generatedDir, { recursive: true });

  const exports: string[] = [];
  for (const [contract, exportName] of Object.entries(CONTRACTS)) {
    const abi = readAbi(contract);
    const body = [
      "// Generated by scripts/gen-abi.ts. Do not edit.",
      `// Source: out/${contract}.sol/${contract}.json`,
      "",
      `export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;`,
      "",
    ].join("\n");
    writeFileSync(join(generatedDir, `${exportName}.ts`), body);
    exports.push(`export { ${exportName} } from "./${exportName}.js";`);
    console.log(`  ${exportName}  (${abi.length} entries)`);
  }

  writeFileSync(
    join(generatedDir, "index.ts"),
    ["// Generated by scripts/gen-abi.ts. Do not edit.", "", ...exports, ""].join("\n"),
  );
  console.log(`wrote ${Object.keys(CONTRACTS).length} ABIs to src/abi/generated/`);
}

main();
